apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: bXktdXNlcm5hbWU=  # Base64 encoded value of 'my-username'
  password: bXktcGFzc3dvcmQ=  # Base64 encoded value of 'my-password'
